name: Run Tests
run-name: ${{ gitea.actor }} is running Rails Tests
on: [push, pull_request]

jobs:
  Rails-Tests:
    runs-on: ubuntu-latest:docker://ruby:3.1.2
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rails test
