name: Run Tests
run-name: ${{ gitea.actor }} is running Rails Tests
on: [push, pull_request]

jobs:
  Rails-Tests:
    runs-on: ruby:3.1.2
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
      - run: |
          ls ${{ github.workspace }}
      - run: |
          echo $PATH
      - run: |
          pwd
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rails test
