name: Run Tests
run-name: ${{ gitea.actor }} is running Rails Tests
on: [push, pull_request]

jobs:
  Rails-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          self-hosted: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rails test
